openapi: 3.0.2
info:
  version: 0.1.0-SNAPSHOT
  title: ${serviceId}-service
servers:
  - url: 'http://localhost:8080/${serviceId}'
paths:
  /hello:
    get:
      description: ${serviceId}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
      tags:
        - ${serviceId}
components:
  schemas:
    Hello:
      type: object
      properties:
        message:
          type: string
          example: 'Hello World'
      x-tags:
        - ${serviceId}
