version: "3.1"
services:
  generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - .:/work
    command: [
      "batch",
      "services/service-angular.yaml",
      "services/service-spring-appservice.yaml",
      "-v"
    ]
    working_dir: /work
  generator2:
    image: openapitools/openapi-generator-cli
    volumes:
      - .:/work
    command: [
      "batch",
      "services/service-spring-controller.yaml",
      "-v"
    ]
    working_dir: /work
    environment:
      JAVA_OPTS: "-Xmx1024M -DloggerPath=conf/log4j.properties -DsupportingFiles"
